version: '3.7'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - 10200:10200
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1g
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maze
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  pgdata:
